//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcEstatus", Namespace="http://schemas.datacontract.org/2004/07/STP")]
    public partial class dcEstatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CausaDevolucionField;
        
        private int CausaDevolucionIDField;
        
        private string MensajeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CausaDevolucion
        {
            get
            {
                return this.CausaDevolucionField;
            }
            set
            {
                this.CausaDevolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CausaDevolucionID
        {
            get
            {
                return this.CausaDevolucionIDField;
            }
            set
            {
                this.CausaDevolucionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEstatusOrdenService")]
public interface IEstatusOrdenService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstatusOrdenService/_EstatusOrden", ReplyAction="http://tempuri.org/IEstatusOrdenService/_EstatusOrdenResponse")]
    STP.dcEstatus _EstatusOrden(int id, string empresa, string folioOrigen, string estado, string causaDevolucion);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstatusOrdenService/_EstatusOrden", ReplyAction="http://tempuri.org/IEstatusOrdenService/_EstatusOrdenResponse")]
    System.Threading.Tasks.Task<STP.dcEstatus> _EstatusOrdenAsync(int id, string empresa, string folioOrigen, string estado, string causaDevolucion);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEstatusOrdenServiceChannel : IEstatusOrdenService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EstatusOrdenServiceClient : System.ServiceModel.ClientBase<IEstatusOrdenService>, IEstatusOrdenService
{
    
    public EstatusOrdenServiceClient()
    {
    }
    
    public EstatusOrdenServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EstatusOrdenServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EstatusOrdenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EstatusOrdenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public STP.dcEstatus _EstatusOrden(int id, string empresa, string folioOrigen, string estado, string causaDevolucion)
    {
        return base.Channel._EstatusOrden(id, empresa, folioOrigen, estado, causaDevolucion);
    }
    
    public System.Threading.Tasks.Task<STP.dcEstatus> _EstatusOrdenAsync(int id, string empresa, string folioOrigen, string estado, string causaDevolucion)
    {
        return base.Channel._EstatusOrdenAsync(id, empresa, folioOrigen, estado, causaDevolucion);
    }
}
